environment:
  APPVEYOR_CACHE_ENTRY_COMPRESSION_LEVEL: Fastest

install:
- nuget restore packages.config -PackagesDirectory packages


cache:
- packages
- c:\go17
#- c:\msys64 -> appveyor.yml
- c:\qt\5.6 -> appveyor.yml

build: off

test_script:
- ps: Set-Content -Path "$env:appveyor_build_folder\packages\ts.txt" -Value "$(get-date)"

#on_finish:
#- ps: Start-sleep -s 1800
