environment:
  APPVEYOR_CACHE_ENTRY_COMPRESSION_LEVEL: Fastest
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -tzip -mx=1

init:
- mklink /J C:\msys64-copy C:\msys64

install:
- nuget restore packages.config -PackagesDirectory packages
- ps: .\cache-hidden.ps1

cache:
- packages
#- c:\go17 -> README.md
- c:\test-folder\
- c:\msys64 -> appveyor.yml
#- c:\msys64-copy -> appveyor.yml
# - c:\qt\5.6 -> README.md

build: off

test_script:
- ps: Set-Content -Path "$env:appveyor_build_folder\packages\ts.txt" -Value "$(get-date)"
- ps: |
    $expected_7zip_path = '"C:\Program Files\7-Zip\7z.exe"'
    Write-Host "Path to 7z: $env:7zip"
    if($env:7zip -ne $expected_7zip_path) { throw "7zip: $env:7zip, expected: $expected_7zip_path"; }
    Write-Host "Clear PATH variable - cache should work"
    $env:path = ""

#on_finish:
#- ps: Start-sleep -s 1800
